on:
  workflow_dispatch:

  schedule:
    - cron: '0 */12 * * *'

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull the image
        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}/flask-app:latest

      - name: Run the image in detached mode
        run: |
          docker run -d --name flask-app -p 80:80 ${{ vars.DOCKER_USERNAME }}/flask-app:latest

      - name: Sleep
        run: |
          sleep 5 
          pip install -r requirements.txt
          chmod +x test_app.py
          python test_app.py

      - name: Check for Success
        id: flag_success
        if: ${{ success() }}
        run: |
          echo "Status=passed" >> $GITHUB_OUTPUT

      - name: Run on failure
        id: flag_failure
        if: ${{ failure()}}
        run: |
          echo "Status=failed" >> $GITHUB_OUTPUT
          
      - name: Stop and remove container
        if: 
        run: |
          docker stop flask-app
          docker rm flask-app
          

      - name: Health Check Report
        if: [[ ${{ steps.flag_success.outputs.status }} == "passed" ]]
        run: |
          echo "## Health Check Report" >> $GITHUB_STEP_SUMMARY
          echo "- Image: flask-app:latest" >> $GITHUB_STEP_SUMMARY
          echo "- Status: PASSED" >> $GITHUB_STEP_SUMMARY
          echo "- Time: $(date)" >> $GITHUB_STEP_SUMMARY

      - name: Health Check Report Failure
        if: [[ ${{ steps.flag_failure.outputs.Status }} == "failed" ]] || ${{ failure() }}
        run: |
          echo "Failed to generate health check report"
       
          