name: PR-pipeline
on:


  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run_tests: true
      python_version: 3.14
  
  dependencies-scan:
    name: Check Dependencies for Vulnerabilities       
    uses: actions/dependency-review-action@v4
    with:
      fail-on-severity: critical



  pr-comment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ ${{needs.build.outputs.test_result }} == 'passed' ];then
            echo "PR Checks passed for branch : ${{ github.head_ref }}"
          else
            echo "PR Checks failed for branch : ${{ github.head_ref }}"
          fi




