name: Build and Push
on:
  workflow_call:

    inputs:
       image_name:
         description: 'holds image name'
         type: string
         required: true

       tag:
         description: holds the tag of the image built
         type: string
         required: true

    secrets:
        docker_username:
          required: true
        docker_token:
          required: true

  
    outputs:
      image_url:
        value: ${{ jobs.reusable-build-and-push.outputs.var }}


jobs:
  reusable-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      var: ${{ steps.image_id.outputs.image_url }}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      
      - run: |
          echo "Secret is set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "Secret is set: ${{ secrets.DOCKER_PASSWORD != '' }}"

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: build image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: image url
        id: image_id
        run: |
          image_url=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}
          echo "image_url=$(cat << 'EOF' $image_url EOF )" >> $GITHUB_OUTPUT


